[aws]
s3_bucket_input_and_script='weclouddata-kfcphuket-input'
s3_bucket_output='weclouddata-kfcphuket-output'
region='ap-southeast-1'
lambda_function_name='batchProject'
lambda_role_name='midtermlambda2'
lambda_layer_name='weCloudProject'
lambda_schedule_rule_name='NightlyInventoryUpload'
lambda_layer_version='7'
glue_role_name='WeCloud-glue-role'
glue_crawler_name='weCloudProject'
ec2_ip_address='ec2-18-143-117-160.ap-southeast-1.compute.amazonaws.com'
account_id='747208718327'
athena_db='weCloudDB'

[email]
sender='mccallum.mitchell@gmail.com'
recipient='mccallum.mitchell@gmail.com'

[airflow]
dag_name='weCloudPipe'

[superset]
container_name='weCloudProject'